<a href="https://colab.research.google.com/github/Nirbhaykushwaha2522/Apexplanet_Task1/blob/main/ApexPlanet_Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TASK 1: Data Immersion & Wrangling

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. DATA ACCESS & FAMILIARIZATION

In [ ]:
# Load dataset
df = pd.read_csv('house_pricing.csv')  # Sample example

In [ ]:
df

    size_sqft  bedrooms   price
0      1200.0       2.0  180000
1      1500.0       3.0  250000
2      1800.0       3.0  290000
3      2000.0       4.0  320000
4      2200.0       4.0  380000
5      1600.0       3.0  240000
6      2500.0       5.0  420000
7      1400.0       NaN  210000
8      3000.0       5.0  550000
9      1700.0       3.0  260000
10     1900.0       3.0  300000
11     2100.0       4.0  360000
12     2300.0       4.0  390000
13     3500.0       3.0  250000
14        NaN       4.0  350000

In [ ]:
df.head() # starting 5 rows

   size_sqft  bedrooms   price
0     1200.0       2.0  180000
1     1500.0       3.0  250000
2     1800.0       3.0  290000
3     2000.0       4.0  320000
4     2200.0       4.0  380000

In [ ]:
# Last 5 rows
df.tail()

    size_sqft  bedrooms   price
10     1900.0       3.0  300000
11     2100.0       4.0  360000
12     2300.0       4.0  390000
13     3500.0       3.0  250000
14        NaN       4.0  350000

In [ ]:
# Shape of data
df.shape

(15, 3)

In [ ]:
# Column details

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   size_sqft  14 non-null     float64
 1   bedrooms   14 non-null     float64
 2   price      15 non-null     int64
dtypes: float64(2), int64(1)
memory usage: 492.0 bytes

In [ ]:
# Statistics summary

df.describe()  # only for numerics

         size_sqft   bedrooms          price
count    14.000000  14.000000      15.000000
mean   2050.000000   3.571429  316666.666667
std     629.712999   0.851631   95068.897322
min    1200.000000   2.000000  180000.000000
25%    1625.000000   3.000000  250000.000000
50%    1950.000000   3.500000  300000.000000
75%    2275.000000   4.000000  370000.000000
max    3500.000000   5.000000  550000.000000

In [ ]:
df.describe(include='all')

         size_sqft   bedrooms          price
count    14.000000  14.000000      15.000000
mean   2050.000000   3.571429  316666.666667
std     629.712999   0.851631   95068.897322
min    1200.000000   2.000000  180000.000000
25%    1625.000000   3.000000  250000.000000
50%    1950.000000   3.500000  300000.000000
75%    2275.000000   4.000000  370000.000000
max    3500.000000   5.000000  550000.000000

In [ ]:
# Create Data Dictionary

data_dict = {
    'Name': ['Jakir', 'Niraj', 'Ashish', 'vikas', 'Kartik'],
    'Age': [18, 17, 19, 23, 35],
    'Marks': [85, 60, 65, 70, 80]
}

In [ ]:
data_dict

{'Name': ['Jakir', 'Niraj', 'Ashish', 'vikas', 'Kartik'],
 'Age': [18, 17, 19, 23, 35],
 'Marks': [85, 60, 65, 70, 80]}

In [ ]:
df = pd.DataFrame(data_dict)

In [ ]:
df

     Name  Age  Marks
0   Jakir   18     85
1   Niraj   17     60
2  Ashish   19     65
3   vikas   23     70
4  Kartik   35     80

In [ ]:

df.shape

(5, 3)

In [ ]:
df.describe()

             Age      Marks
count   5.000000   5.000000
mean   22.400000  72.000000
std     7.402702  10.368221
min    17.000000  60.000000
25%    18.000000  65.000000
50%    19.000000  70.000000
75%    23.000000  80.000000
max    35.000000  85.000000

In [ ]:

df.dtypes.values

array([dtype('O'), dtype('int64'), dtype('int64')], dtype=object)

In [ ]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [ ]:

df.to_csv('df.csv', index = False)

In [ ]:

df

     Name  Age  Marks
0   Jakir   18     85
1   Niraj   17     60
2  Ashish   19     65
3   vikas   23     70
4  Kartik   35     80

2. DATA QUALITY ASSESSMENT

In [ ]:
# Missing value

df = sns.load_dataset('iris')  # load data in seaborn library

In [ ]:

df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:

df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
# Duplicate rows

df.duplicated().sum()

np.int64(1)

In [ ]:
# Check inconsistent formatting (example)
for col in df.select_dtypes(include='object'):
  print(col,':',df[col].unique())

species : ['setosa' 'versicolor' 'virginica']

3. DATA CLEANING & TRANSFORMATION

In [ ]:

#  Remove duplicate rows

df = df.drop_duplicates()

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[149 rows x 5 columns]

In [ ]:

#  Remove duplicate rows

df = df.drop_duplicates()

In [ ]:
# Convert date column to proper format

if "Date_of_Birth" in df.columns:
    df["Date_of_Birth"] = pd.to_datetime(df["Date_of_Birth"], errors='coerce')

In [ ]:
# Feature Engineering Example: Create Age

if "Date_of_Birth" in df.columns:
    df["Age"] = (pd.Timestamp("today") - df["Date_of_Birth"]).dt.days

In [ ]:
# Standardize text (example: CustomerName)

if "CustomerName" in df.columns:
    df["CustomerName"] = df["CustomerName"].str.title().str.strip()

In [ ]:
# Convert columns to lowercase for consistency

df.columns = df.columns.str.lower().str.replace(" ", "_")